### ISSUE TITLE
should the `S[-1]` be `T[-1]`  in the following line

### ISSUE THREAD

**Issue by g2384** [vkhamesi/ocpdet#10] opened 2023-07-23 12:02 UTC
https://github.com/vkhamesi/ocpdet/blob/26ad9ff239447f10dbcbe5dfb1c3fa419c8bd1e8/ocpdet/CUSUM.py#L100C30-L100C36

should the `S[-1]` be `T[-1]`  in the following line?

```py
        self.T.append(
            max(0, self.S[-1] - (data_new - self.mu) / self.sigma - self.k))
```

**Comment by vkhamesi** [comment] 2023-07-25 11:13
Correct, probably a typo. The issue is now fixed, thanks for pointing it out!

**Closed by vkhamesi** 2023-07-25 11:13 UTC
